### ISSUE TITLE
Error message on Cloud Run deployment

### ISSUE THREAD

**Issue by addadda023** [minimaxir/gpt-2-cloud-run#12]
This issue has to do with deploying in google cloud run. The app run runs in local docker container, i.e., curl http://0.0.0.0:8080 returns desired output. I then followed the rest of the instructions to deploy in google cloud run -- set the memory to 2GB & set max requests to 1. The deployment however wasn't successful.

`Cloud Run error: Container failed to start. Failed to start and then listen on the port defined by the PORT environment variable. Logs for this revision might contain more information.`

A cursory search says that GCP expects requests on 0.0.0.0:8080. This is what app.py stores too, so not sure where the deployment error is coming from. Any idea?

**Comment by addadda023** [comment]
It was an issue with google cloud. The image was served finally after I tried multiple times.

**Comment by arieltoledo** [comment]
@addadda023 Hi, I'm having the same issue with cloud run, I deployed like 10 times by now with no luck. Wonder how you did it ?

**Comment by estelle-elizabeth** [comment]
Make sure to increase memory allocated to 2 GiB (https://cloud.google.com/run/docs/configuring/memory-limits)
